language: node_js
sudo: false
cache: apt
addons:
  apt:
    packages:
    - python-demjson
    - python-yaml
node_js:
  - "0.10"
install:
  - npm install carto@0.16.0
  - mkdir -p data/world_boundaries data/simplified-land-polygons-complete-3857 data/ne_110m_admin_0_boundary_lines_land data/ne_10m_populated_places data/land-polygons-split-3857
  - touch data/world_boundaries/builtup_area.shp data/simplified-land-polygons-complete-3857/simplified_land_polygons.shp data/ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp data/ne_10m_populated_places/ne_10m_populated_places_fixed.shp data/land-polygons-split-3857/land_polygons.shp
script:
  - set -o pipefail && ./node_modules/carto/bin/carto project.mml | xmllint - | wc -l
  - find symbols/ -name '*.svg' | xargs xmllint --noout
